apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.postgre.volumeClaimName}}
  namespace: {{ .Values.postgre.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi