apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgre.name }}
  namespace: {{ .Values.postgre.namespace }}
spec:
  ports:
    - port: {{ .Values.postgre.port }}
      targetPort: {{ .Values.postgre.port }}
      protocol: TCP
      name: postgres
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.postgre.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

