apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.postgre.volumeName}}
  namespace: {{ .Values.postgre.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"