kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.ssc.name }}
  namespace: {{ .Values.ssc.namespace }}
subjects:
# GCP user account
{{- range .Values.ssc.roleBindings }}
  - kind: {{ .kind }}
    name: {{ .name }}
{{- end }}
roleRef:
  kind: Role
  name: {{ .Values.ssc.name }}
  apiGroup: rbac.authorization.k8s.io