apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ssc.user.name }}
  namespace: {{ .Values.ssc.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.ssc.user.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.ssc.user.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.ssc.imagePullSecret }}
      containers:
        - name: {{ .Values.ssc.user.name }}
          image: {{ .Values.ssc.user.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.ssc.user.env }}
          env:
          {{- range .Values.ssc.user.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.ssc.user.port }}
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
