apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ssc.serviceaccount }}
  namespace: {{ .Values.ssc.namespace }}
  labels:
    {{- include "k8sTest.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
